server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    bus:
      destination: bus-refresh-topic
    config:
      server:
        git:
          uri: https://github.com/lotteon2/jeontongju-config
          username: ${GITHUB_USERID}
          password: ${GITHUB_TOKEN}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
